/*
 * Jakefile
 * PlayPush
 *
 * Created by Leif Singer on December 26, 2009.
 * Copyright 2009, Leif Singer All rights reserved.
 */

var ENV = require("system").env,
    FILE = require("file"),
    task = require("jake").task,
    FileList = require("jake").FileList,
    app = require("cappuccino/jake").app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("PlayPush", function(task)
{
    task.setBuildIntermediatesPath(FILE.join("Build", "PlayPush.build", configuration));
    task.setBuildPath(FILE.join("Build", configuration));

    task.setProductName("PlayPush");
    task.setIdentifier("com.yourcompany.PlayPush");
    task.setVersion("1.0");
    task.setAuthor("Leif Singer");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("PlayPush");
    task.setSources(new FileList("**/*.j"));
    task.setResources(new FileList("Resources/*"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["PlayPush"]);
